package com.actas.ems.DTO.Elvlrt;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class App03ElvlrtDto {
    private String frdate;
    private String todate;
    private String recedate;
    private String recedateyear;
    private String recenum;
    private String recetime;
    private String hitchdate;
    private String hitchhour;
    private String actcd;
    private String actnm;
    private String equpcd;
    private String equpnm;
    private Long cnt;
    private Long ascnt;
    private String actpernm;
    private String divinm;
    private String perid;
    private String pernm;
    private String contcd;
    private String contnm;
    private String contremark;
    private String resunm;
    private String resuremark;
    private String jejak;
    private String model;
    private String yyyymm;
    private String reperid;
    private String repernm;
    private String remonm;
    private String remoremark;
    private String greginm;
    private String reginm;
    private String result;
    private String compdate;
    private String arrivtime;
    private String comptime;
    private String resutime;
    private String resulttime;
    private String resultnm;
    private String tel;
    private String addrtxt;
    private String teltime;
    private String telxcoordi;
    private String telycodrdi;
    private String handphone;
    private Long callcount;
    private Long rececnt;
    private Long callback;
    private Long compcnt;
    private String contents;
    private String remark;
    private String calldate;
    private String calltime;
    private String callnm;
    private String custflag;
    private String seq;
    private String subcalldate;
    private String subcalltime;
    private String callnum;
    private String flag;
    private String callmemo;
    private String rcvflag;
    private String callendmemo;
    private String callbackflag;
    private String callbacktime;
    private String callbackmemo;

}
